name: CI

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-lastest
    steps: 
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v2
      - run: bazel build //...
      - run: bazel test //...
